<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Photo;
use App\Models\Poi;

class PhotosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('photos')->delete();

        $photos = [
            [
                'title' => 'Lavaux vineyards',
                'descr' => 'Chexbres vineyards in late summer',
                'author' => 'Soumya Basu',
                'year' => 2018,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Lavaux_vineyards.jpg',
                'poi_id' => Poi::where('title', 'Terrasses de Lavaux')->value('id'),
            ],
            [
                'title' => 'Schweiz Schloss Chillon Gesamtansicht',
                'descr' => 'Castle Chillon at Lake Geneva, Switzerland',
                'author' => 'Benjamin Gimmel',
                'year' => 2005,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Schweiz_Schloss_Chillon_Gesamtansicht.jpg',
                'poi_id' => Poi::where('title', 'Château de Chillon')->value('id'),
            ],
            [
                'title' => 'Montreux Les Rochers-de-Naye 2018 finish',
                'descr' => 'Vue sur la gare des Rochers-de-Naye et l\'arrivée de la course Montreux-Les-Rochers-de-Naye 2018',
                'author' => 'Johann Conus',
                'year' => 2018,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Montreux_Les_Rochers-de-Naye_2018_finish.jpg',
                'poi_id' => Poi::where('title', 'Montreux - Rochers-de-Naye')->value('id'),
            ],
            [
                'title' => 'Museo Olímpico (Lausana)',
                'descr' => 'Image of the facade of the Olympic Museum in Lausanne, Switzerland. People are seen entering the museum through this entrance.',
                'author' => 'ProtoplasmaKid',
                'year' => 2022,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Museo_Ol%C3%ADmpico_%28Lausana%29_-_2.jpg',
                'poi_id' => Poi::where('title', 'Musée Olympique')->value('id'),
            ],
            [
                'title' => 'ManoirdeBan',
                'descr' => 'Image of Manoir de Ban',
                'author' => 'Tahdrummond',
                'year' => 2012,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/8/85/ManoirdeBan.jpg',
                'poi_id' => Poi::where('title', 'Chaplin\'s World')->value('id'),
            ],
            [
                'title' => 'Cathédrale de Lausanne depuis le Champ de l\'Air',
                'descr' => 'La cathédrale de Lausanne (Suisse) vue depuis le lieu-dit du Champ de l\'Air',
                'author' => 'Gzzz',
                'year' => 2009,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Cath%C3%A9drale_de_Lausanne_depuis_le_Champ_de_l%27Air.JPG',
                'poi_id' => Poi::where('title', 'Cathédrale de Lausanne')->value('id'),
            ],
            [
                'title' => 'Grottes de Vallorbe',
                'descr' => '',
                'author' => 'Jurate Daugelaite',
                'year' => 2018,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Grottes_de_Vallorbe.jpg',
                'poi_id' => Poi::where('title', 'Grottes de Vallorbe')->value('id'),
            ],
            [
                'title' => 'Espace Horloger de la Vallée de Joux',
                'descr' => '',
                'author' => 'DarDarCH',
                'year' => 2018,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Espace_Horloger_de_la_Vall%C3%A9e_de_Joux_-_03.jpg',
                'poi_id' => Poi::where('title', 'Espace Horloger')->value('id'),
            ],
            [
                'title' => 'Tour de Sauvabelin Lausanne',
                'descr' => 'La Tour de Sauvabelin, dans le bois du même nom (Lausanne, Suisse)',
                'author' => 'Gzzz',
                'year' => 2013,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/0/09/Tour_de_Sauvabelin_Lausanne.jpg',
                'poi_id' => Poi::where('title', 'Tour de Sauvabelin')->value('id'),
            ],
            [
                'title' => 'Corseaux, Switzerland - panoramio',
                'descr' => 'Lavaux Vinorama, Rivaz, Switzerland',
                'author' => 'Ben Bender',
                'year' => 2015,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/8/86/Corseaux%2C_Switzerland_-_panoramio_%282%29.jpg',
                'poi_id' => Poi::where('title', 'Lavaux Vinorama')->value('id'),
            ],
            [
                'title' => 'Musée de l\'Elysée',
                'descr' => 'Campagne de l\'Élysée in Lausanne',
                'author' => 'Sandro Senn',
                'year' => 2009,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/5/55/Mus%C3%A9e_de_l%27Elys%C3%A9e_4.jpg',
                'poi_id' => Poi::where('title', 'Musée de l’Élysée')->value('id'),
            ],
            [
                'title' => 'Vevey, Alimentarium',
                'descr' => 'Suisse, canton de Vaud, Vevey, Alimentarium, Fondation de la Maison Nestlé, ouvert en juin 1985. Ce musée a pour but de cerner les problèmes liés à l\'alimentation d\'hier et d\'aujourd\'hui. Nombreuses expositions temporaires.',
                'author' => 'Odrade123',
                'year' => 2011,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Vevey%2C_Alimentarium_4.jpg',
                'poi_id' => Poi::where('title', 'Alimentarium')->value('id'),
            ],
            [
                'title' => 'Maison d\'Ailleurs',
                'descr' => 'Maison d\'Ailleurs',
                'author' => 'Nicolas Nova',
                'year' => 2008,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Maison_d%27Ailleurs_%283085712116%29.jpg',
                'poi_id' => Poi::where('title', 'Maison d’Ailleurs')->value('id'),
            ],
            [
                'title' => 'Musee Jenisch',
                'descr' => 'Le musée Jenisch Vevey, inauguré le 10 mars 1897 à Vevey en Suisse, est un musée d’art.',
                'author' => 'Dirrival',
                'year' => 2012,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/8/88/Musee_Jenisch.jpg',
                'poi_id' => Poi::where('title', 'Musée Jenisch')->value('id'),
            ],
            [
                'title' => 'Fondation de l’Hermitage + Park',
                'descr' => 'Herrenhaus mit Park und Museum',
                'author' => 'Geri340',
                'year' => 2010,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/3/34/Fondation_de_l%E2%80%99Hermitage_%2B_Park.JPG',
                'poi_id' => Poi::where('title', 'Fondation de l’Hermitage')->value('id'),
            ],
            [
                'title' => 'Signal de Bougy',
                'descr' => 'Petit plan d\'eau au parc du Pré-Vert au Signal de Bougy (canton de Vaud, Suisse)',
                'author' => 'Ji-Elle',
                'year' => 2012,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/6/66/Signal_de_Bougy_%281%29.jpg',
                'poi_id' => Poi::where('title', 'Signal de Bougy')->value('id'),
            ],
            [
                'title' => 'Façade Musée Pully',
                'descr' => 'Façade du musée de Pully',
                'author' => 'Mourad Ben Abdallah',
                'year' => 2022,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/4/42/Fa%C3%A7ade_Mus%C3%A9e_Pully.jpg',
                'poi_id' => Poi::where('title', 'Musée de Pully')->value('id'),
            ],
            [
                'title' => 'Grandson-Vaud',
                'descr' => 'Grandson, une commune suisse du canton de Vaud, située dans le district du Jura-Nord vaudois, vue aérienne',
                'author' => 'Alexey M.',
                'year' => 2015,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Grandson-Vaud.JPG',
                'poi_id' => Poi::where('title', 'Château de Grandson')->value('id'),
            ],
            [
                'title' => 'CDV musee expo permanente',
                'descr' => 'Salle de l\'exposition permanente du musée de la Confrérie des Vignerons',
                'author' => 'Sabine Carruzzo',
                'year' => 2020,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/c/c6/CDV_musee_expo_permanente.jpg',
                'poi_id' => Poi::where('title', 'Musée de la Confrérie des Vignerons')->value('id'),
            ],
            [
                'title' => 'Château d\'Aigle 2022',
                'descr' => 'Le château d\'Aigle, en Suisse, en juillet 2022.',
                'author' => 'Christian David',
                'year' => 2022,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Ch%C3%A2teau_d%27Aigle_2022_%281%29.jpg',
                'poi_id' => Poi::where('title', 'Château d\'Aigle')->value('id'),
            ],
            [
                'title' => 'Musee Bolo',
                'descr' => 'View of the Musée Bolo',
                'author' => 'Yves Bolognini & Musée Bolo',
                'year' => 2012,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Musee_Bolo_-_5735.JPG',
                'poi_id' => Poi::where('title', 'Musée Bolo')->value('id'),
            ],
            [
                'title' => 'Wild Bumblebee in flight pollinating with Crocus Parc naturel régional Jura vaudois Photo by Giles Laurent',
                'descr' => 'Bourdon sauvage en vol pollinisant avec des crocus au Parc naturel régional Jura vaudois',
                'author' => 'Giles Laurent',
                'year' => 2022,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/e/e1/061_Wild_Bumblebee_in_flight_pollinating_with_Crocus_Parc_naturel_r%C3%A9gional_Jura_vaudois_Photo_by_Giles_Laurent.jpg',
                'poi_id' => Poi::where('title', 'Parc Naturel Jura Vaudois')->value('id'),
            ],
            [
                'title' => 'Aquatis Lausanne',
                'descr' => 'Aquatis, musée vivant sur le thème de l\'eau douce comportant un aquarium et un vivarium, situé à Lausanne, en Suisse.',
                'author' => 'Gzzz',
                'year' => 2020,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/7/76/Aquatis_Lausanne_%283%29.jpg',
                'poi_id' => Poi::where('title', 'Aquatis Aquarium-Vivarium')->value('id'),
            ],
            [
                'title' => 'Musée Romain Lausanne',
                'descr' => 'Musée romain de Lausanne-Vidy (Suisse).',
                'author' => 'Gzzz',
                'year' => 2020,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Mus%C3%A9e_Romain_Lausanne_%281%29.jpg',
                'poi_id' => Poi::where('title', 'Musée romain de Lausanne-Vidy')->value('id'),
            ],
            [
                'title' => 'La Maison du Blé et du Pain à Echallens',
                'descr' => 'La Maison du Blé et du Pain à son ouverture',
                'author' => 'Lospinguinos',
                'year' => 2007,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/4/46/La_Maison_du_Bl%C3%A9_et_du_Pain_%C3%A0_Echallens.jpg',
                'poi_id' => Poi::where('title', 'Maison du Blé et du Pain')->value('id'),
            ],
            [
                'title' => 'La Victoire (barque)',
                'descr' => 'La Victoire, barque du Léman. Construite au Locum en 1926. Modèle réduit au 1:14 par Pierre Cochard d\'après les plans de Gérard Cornaz. Exposé au musée du Vieux Montreux.',
                'author' => 'Jmh2o',
                'year' => 2011,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/3/33/La_Victoire_%28barque%29_-_1.jpg',
                'poi_id' => Poi::where('title', 'Musée du Vieux Montreux')->value('id'),
            ],
            [
                'title' => 'Musée Suisse du Jeu',
                'descr' => 'Photo du Château de la Tour-de-Peilz qui abrite le Musée Suisse du Jeu',
                'author' => 'MSjeu',
                'year' => 2008,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Mus%C3%A9e_Suisse_du_Jeu.JPG',
                'poi_id' => Poi::where('title', 'Musée Suisse du Jeu')->value('id'),
            ],
            [
                'title' => 'Château de Morges - façade',
                'descr' => 'Château vu de face à l\'entrée',
                'author' => 'Djaquet',
                'year' => 2006,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/8/83/Ch%C3%A2teau_de_Morges_-_fa%C3%A7ade.jpg',
                'poi_id' => Poi::where('title', 'Château de Morges')->value('id'),
            ],
            [
                'title' => 'MJBC-jardin-la-Thomasia-Bex-CH',
                'descr' => 'Vue sur le jardin alpin, la Thomasia, près de Bex, Switerland. Il fait partie du Musée et jardins botaniques cantonaux, Canton de Vaud.',
                'author' => 'Musée et jardins botaniques cantonaux',
                'year' => 2009,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/3/33/MJBC-jardin-la-Thomasia-Bex-CH-1.jpg',
                'poi_id' => Poi::where('title', 'Le Jardin Botanique de Lausanne')->value('id'),
            ],
            [
                'title' => 'Lausanne, ancien évêché et Musée historique de Lausanne, entré',
                'descr' => 'Suisse, canton de Vaud, Lausanne, ancien évêché et Musée historique de Lausanne. Construit en l\'an mil comme résidence épiscopale, utilisé par la suite comme prison, tribunal et école, il devient le Musée historique de Lausanne en 1989.',
                'author' => 'Odrade123',
                'year' => 2011,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Lausanne%2C_ancien_%C3%A9v%C3%AAch%C3%A9_et_Mus%C3%A9e_historique_de_Lausanne%2C_entr%C3%A9.jpg',
                'poi_id' => Poi::where('title', 'Musée Historique de Lausanne')->value('id'),
            ],
            [
                'title' => 'Champ de bataille, by Denis Rouèche, Parc de Mon-Repos, Lausanne',
                'descr' => 'Champ de bataille, by Denis Rouèche, Parc de Mon-Repos, Lausanne.',
                'author' => 'Sissssou',
                'year' => 2015,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Champ_de_bataille%2C_by_Denis_Rou%C3%A8che%2C_Parc_de_Mon-Repos%2C_Lausanne.JPG',
                'poi_id' => Poi::where('title', 'Parc de Mon Repos')->value('id'),
            ],
            [
                'title' => 'Eglise Saint-François Lausanne',
                'descr' => 'L\'Église Saint-François à Lausanne.',
                'author' => 'Gzzz',
                'year' => 2020,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Eglise_Saint-Fran%C3%A7ois_Lausanne.jpg',
                'poi_id' => Poi::where('title', 'Église Saint-François')->value('id'),
            ],
            [
                'title' => 'Musee de la main',
                'descr' => 'Façade du musée de la Main',
                'author' => 'Wikitraits',
                'year' => 2015,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/d/df/Musee_de_la_main.JPG',
                'poi_id' => Poi::where('title', 'Musée de la Main UNIL-CHUV')->value('id'),
            ],
            [
                'title' => 'Place de la Palud déserte',
                'descr' => 'La place de la Palud de Lausanne (Suisse), déserte le lundi de Pâques pendant le confinement demandé pendant la pandémie de COVID-19.',
                'author' => 'Gzzz',
                'year' => 2020,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Place_de_la_Palud_d%C3%A9serte_%282%29.jpg',
                'poi_id' => Poi::where('title', 'Place de la Palud')->value('id'),
            ],
            [
                'title' => 'Musée Alexis Forel Morges',
                'descr' => 'Vue du bâtiment du musée depuis l\'entrée située sur la Grand-Rue 54, à Morges',
                'author' => 'MuseeForel',
                'year' => 2024,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Mus%C3%A9e_Alexis_Forel_Morges.png',
                'poi_id' => Poi::where('title', 'Musée Alexis Forel')->value('id'),
            ],
            [
                'title' => 'Maison de la Rivière Tolochenaz',
                'descr' => 'Le canal dévié du Boiron, à Tolochenaz (Suisse), à l\'endroit où il se jette à nouveau dans le Boiron après avoir traversé le site de la Maison de la Rivière, centre dédié à la vie aquatique.',
                'author' => 'Gzzz',
                'year' => 2015,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/8/81/Maison_de_la_Rivi%C3%A8re_Tolochenaz_4.jpg',
                'poi_id' => Poi::where('title', 'La Maison de la Rivière')->value('id'),
            ],
            [
                'title' => 'Les pléiades',
                'descr' => 'Wiese mit Weißen Narzissen auf Les Pléiades',
                'author' => 'albinfo',
                'year' => 2011,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Les_pl%C3%A9iades_20.jpg',
                'poi_id' => Poi::where('title', 'Les Pléiades')->value('id'),
            ],
            [
                'title' => 'Château Saint-Maire Lausanne 2020',
                'descr' => 'Le château Saint-Maire de Lausanne, en Suisse. Il abrite actuellement le siège du Conseil d\'État du Canton de Vaud.',
                'author' => 'Gzzz',
                'year' => 2020,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/7/74/Ch%C3%A2teau_Saint-Maire_Lausanne_2020.jpg',
                'poi_id' => Poi::where('title', 'Château de La Sarraz')->value('id'),
            ],
            [
                'title' => '',
                'descr' => '',
                'author' => '',
                'year' => 1970,
                'link' => asset('storage/images/pois/poi-default-photo.jpg'),
                'poi_id' => Poi::where('title', 'Espace des Inventions')->value('id'),
            ],
            [
                'title' => '',
                'descr' => '',
                'author' => '',
                'year' => 1970,
                'link' => asset('storage/images/pois/poi-default-photo.jpg'),
                'poi_id' => Poi::where('title', 'Château Saint-Maire')->value('id'),
            ],
            [
                'title' => '',
                'descr' => '',
                'author' => '',
                'year' => 1970,
                'link' => asset('storage/images/pois/poi-default-photo.jpg'),
                'poi_id' => Poi::where('title', 'Domaine Croix Duplex')->value('id'),
            ],
            [
                'title' => '',
                'descr' => '',
                'author' => '',
                'year' => 1970,
                'link' => asset('storage/images/pois/poi-default-photo.jpg'),
                'poi_id' => Poi::where('title', 'Caveau de Dézaley')->value('id'),
            ],
            [
                'title' => '',
                'descr' => '',
                'author' => '',
                'year' => 1970,
                'link' => asset('storage/images/pois/poi-default-photo.jpg'),
                'poi_id' => Poi::where('title', 'Lakeside Promenade')->value('id'),
            ],
            [
                'title' => 'Statue of Freddie Mercury in Montreux',
                'descr' => 'Vue sur la statue de Freddie Mercury, un monument rendant hommage au chanteur légendaire de Queen, à Montreux, en Suisse.',
                'author' => '	Bernd Brägelmann',
                'year' => 2005,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/8/80/Statue_of_Freddie_Mercury_in_Montreux_2005-07-15.jpg',
                'poi_id' => Poi::where('title', 'Statue de Freddie Mercury')->value('id'),
            ],
            [
                'title' => 'Montreux Casino Night',
                'descr' => '',
                'author' => 'Abhijeet Rane',
                'year' => 2008,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/c/c0/Montreux_Casino_Night.jpg',
                'poi_id' => Poi::where('title', 'Casino de Montreux')->value('id'),
            ],
            [
                'title' => '',
                'descr' => '',
                'author' => '',
                'year' => 1970,
                'link' => asset('storage/images/pois/poi-default-photo.jpg'),
                'poi_id' => Poi::where('title', 'Vignoble en terrasses (chemin de randonnée)')->value('id'),
            ],
            [
                'title' => '',
                'descr' => '',
                'author' => '',
                'year' => 1970,
                'link' => asset('storage/images/pois/poi-default-photo.jpg'),
                'poi_id' => Poi::where('title', 'Läderach - Chocolatier Suisse')->value('id'),
            ],
            [
                'title' => 'Palais de Rumine',
                'descr' => 'Palais de Rumine, Lausanne, Suisse',
                'author' => 'Urs Zeier',
                'year' => 2008,
                'link' => 'https://upload.wikimedia.org/wikipedia/commons/1/16/Palais_de_Rumine_1.jpg',
                'poi_id' => Poi::where('title', 'Palais de Rumine')->value('id'),
            ],
        ];


        foreach ($photos as $photo) {
            Photo::create($photo);
        }
    }
}
