<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Poi;
use Illuminate\Support\Facades\DB;

class PoisTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('poi_histories')->delete();
        DB::table('path_poi')->delete();
        DB::table('poi_facts')->delete();
        DB::table('photos')->delete();
        DB::table('audio')->delete();
        DB::table('answers')->delete();
        DB::table('questions')->delete();
        DB::table('quizzes')->delete();
        DB::table('links')->delete();
        DB::table('pois')->delete();

        $pois = [
            [
                'title' => 'Terrasses de Lavaux',
                'short_descr' => 'Site du patrimoine mondial de l\'UNESCO.',
                'descr' => 'Les terrasses de Lavaux offrent des vues spectaculaires et témoignent de siècles de viticulture.',
                'adress_label' => 'Lavaux, Vaud, Suisse',
                'lat' => 46.4900,
                'long' => 6.7417,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Château de Chillon',
                'short_descr' => 'Château médiéval sur une île.',
                'descr' => 'Le château de Chillon, situé sur le lac Léman, est l\'un des bâtiments historiques les plus visités de Suisse.',
                'adress_label' => 'Avenue de Chillon 21, 1820 Veytaux, Suisse',
                'lat' => 46.4140,
                'long' => 6.9276,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Montreux - Rochers-de-Naye',
                'short_descr' => 'Chemin de fer de montagne pittoresque.',
                'descr' => 'Ce chemin de fer offre des vues spectaculaires du lac Léman aux Alpes, culminant aux Rochers-de-Naye.',
                'adress_label' => 'Montreux, Vaud, Suisse',
                'lat' => 46.4418,
                'long' => 6.9259,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Musée Olympique',
                'short_descr' => 'Musée dédié aux Jeux Olympiques.',
                'descr' => 'Situé à Lausanne, ce musée présente l\'histoire des Jeux Olympiques à travers des expositions interactives.',
                'adress_label' => 'Quai d\'Ouchy 1, 1006 Lausanne, Suisse',
                'lat' => 46.5155,
                'long' => 6.6327,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Chaplin\'s World',
                'short_descr' => 'Musée dédié à Charlie Chaplin.',
                'descr' => 'Chaplin\'s World est situé dans l\'ancienne maison de Charlie Chaplin à Corsier-sur-Vevey, offrant une plongée dans sa vie et son œuvre.',
                'adress_label' => 'Route de Fenil 2, 1804 Corsier-sur-Vevey, Suisse',
                'lat' => 46.4716,
                'long' => 6.8422,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Cathédrale de Lausanne',
                'short_descr' => 'Cathédrale gothique.',
                'descr' => 'Cette magnifique cathédrale gothique est un point central de Lausanne, connue pour son architecture impressionnante et son importance historique.',
                'adress_label' => 'Place de la Cathédrale, 1005 Lausanne, Suisse',
                'lat' => 46.5222,
                'long' => 6.6358,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Tour de Sauvabelin',
                'short_descr' => 'Tour d\'observation en bois.',
                'descr' => 'Offrant des vues panoramiques sur Lausanne et le lac Léman, la Tour de Sauvabelin est un lieu populaire pour les visiteurs.',
                'adress_label' => 'Chemin des Celtes, 1018 Lausanne, Suisse',
                'lat' => 46.5301,
                'long' => 6.6458,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Lavaux Vinorama',
                'short_descr' => 'Musée du vin et dégustation.',
                'descr' => 'Situé au cœur des vignobles de Lavaux, ce lieu offre une expérience immersive dans la culture viticole locale.',
                'adress_label' => 'Route du Lac 2, 1096 Bourg-en-Lavaux, Suisse',
                'lat' => 46.4886,
                'long' => 6.7262,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Grottes de Vallorbe',
                'short_descr' => 'Spectaculaires grottes calcaires.',
                'descr' => 'Ces grottes impressionnantes comptent parmi les plus belles de Suisse, avec des stalactites et des stalagmites stupéfiantes.',
                'adress_label' => 'Chemin des Grottes 30, 1337 Vallorbe, Suisse',
                'lat' => 46.7102,
                'long' => 6.3816,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Espace Horloger',
                'short_descr' => 'Musée de l\'horlogerie.',
                'descr' => 'Situé dans la Vallée de Joux, ce musée présente l\'histoire et l\'art de l\'horlogerie suisse.',
                'adress_label' => 'Rue de l\'Industrie 2, 1347 Le Sentier, Suisse',
                'lat' => 46.6082,
                'long' => 6.2307,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Musée de l’Élysée',
                'short_descr' => 'Musée de la photographie.',
                'descr' => 'Situé à Lausanne, ce musée est dédié à l\'art de la photographie, avec une collection riche et variée.',
                'adress_label' => 'Avenue de l\'Elysée 18, 1014 Lausanne, Suisse',
                'lat' => 46.5086,
                'long' => 6.6368,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Alimentarium',
                'short_descr' => 'Musée de l\'alimentation.',
                'descr' => 'Situé à Vevey, l\'Alimentarium explore l\'histoire et les cultures de l\'alimentation à travers des expositions interactives.',
                'adress_label' => 'Quai Perdonnet 25, 1800 Vevey, Suisse',
                'lat' => 46.4591,
                'long' => 6.8449,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Maison d’Ailleurs',
                'short_descr' => 'Musée de la science-fiction.',
                'descr' => 'Situé à Yverdon-les-Bains, ce musée unique est consacré à la science-fiction, l’utopie et les voyages extraordinaires.',
                'adress_label' => 'Place Pestalozzi 14, 1400 Yverdon-les-Bains, Suisse',
                'lat' => 46.7788,
                'long' => 6.6416,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Musée Jenisch',
                'short_descr' => 'Musée des beaux-arts.',
                'descr' => 'Ce musée à Vevey abrite une collection impressionnante d\'art suisse et international, y compris des œuvres graphiques.',
                'adress_label' => 'Avenue de la Gare 2, 1800 Vevey, Suisse',
                'lat' => 46.4602,
                'long' => 6.8427,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Fondation de l’Hermitage',
                'short_descr' => 'Musée et centre d\'art.',
                'descr' => 'Ce centre d\'art à Lausanne offre des expositions temporaires dans un cadre magnifique avec vue sur la ville et le lac Léman.',
                'adress_label' => 'Route du Signal 2, 1018 Lausanne, Suisse',
                'lat' => 46.5252,
                'long' => 6.6385,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Signal de Bougy',
                'short_descr' => 'Parc de loisirs et de détente.',
                'descr' => 'Ce parc offre des activités pour toute la famille, avec des vues panoramiques sur le lac Léman et les Alpes.',
                'adress_label' => 'Route du Signal, 1172 Bougy-Villars, Suisse',
                'lat' => 46.4823,
                'long' => 6.3476,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Musée de Pully',
                'short_descr' => 'Musée d\'histoire locale.',
                'descr' => 'Le musée de Pully présente l\'histoire et le patrimoine de la région, avec des expositions sur l\'archéologie et l\'histoire locale.',
                'adress_label' => 'Avenue du Prieuré 2, 1009 Pully, Suisse',
                'lat' => 46.5094,
                'long' => 6.6615,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Château de Grandson',
                'short_descr' => 'Château médiéval.',
                'descr' => 'Le château de Grandson est un magnifique château médiéval surplombant le lac de Neuchâtel, avec des expositions sur l\'histoire régionale.',
                'adress_label' => 'Rue Haute 11, 1422 Grandson, Suisse',
                'lat' => 46.8073,
                'long' => 6.6449,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Musée de la Confrérie des Vignerons',
                'short_descr' => 'Musée de la viticulture.',
                'descr' => 'Ce musée à Vevey est dédié à la célèbre Fête des Vignerons et à la tradition viticole de la région.',
                'adress_label' => 'Rue du Château 2, 1800 Vevey, Suisse',
                'lat' => 46.4582,
                'long' => 6.8461,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Château d\'Aigle',
                'short_descr' => 'Château et musée du vin.',
                'descr' => 'Le château d\'Aigle abrite un musée dédié à l\'histoire du vin et offre une vue imprenable sur les vignobles environnants.',
                'adress_label' => 'Place du Château, 1860 Aigle, Suisse',
                'lat' => 46.3183,
                'long' => 6.9694,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Musée Bolo',
                'short_descr' => 'Musée de l\'informatique.',
                'descr' => 'Le Musée Bolo à Lausanne est dédié à l\'histoire de l\'informatique et des ordinateurs, avec des expositions interactives.',
                'adress_label' => 'Route de la Maladière 71, 1022 Chavannes-près-Renens, Suisse',
                'lat' => 46.5296,
                'long' => 6.5800,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Parc Naturel Jura Vaudois',
                'short_descr' => 'Parc naturel protégé.',
                'descr' => 'Ce parc naturel offre des paysages magnifiques, des sentiers de randonnée et une faune diversifiée dans le Jura vaudois.',
                'adress_label' => 'Col du Marchairuz, 1348 Le Brassus, Suisse',
                'lat' => 46.5700,
                'long' => 6.2183,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Aquatis Aquarium-Vivarium',
                'short_descr' => 'Aquarium et vivarium.',
                'descr' => 'Situé à Lausanne, Aquatis est le plus grand aquarium-vivarium d\'eau douce en Europe, présentant des espèces aquatiques du monde entier.',
                'adress_label' => 'Route de Berne 144, 1010 Lausanne, Suisse',
                'lat' => 46.5346,
                'long' => 6.6618,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Musée romain de Lausanne-Vidy',
                'short_descr' => 'Musée archéologique.',
                'descr' => 'Ce musée présente les découvertes archéologiques de la ville romaine de Lousonna, avec des objets et des reconstitutions historiques.',
                'adress_label' => 'Chemin du Bois-de-Vaux 24, 1007 Lausanne, Suisse',
                'lat' => 46.5162,
                'long' => 6.6091,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Maison du Blé et du Pain',
                'short_descr' => 'Musée du blé et du pain.',
                'descr' => 'Située à Echallens, cette maison présente l\'histoire et les techniques de la culture du blé et de la fabrication du pain.',
                'adress_label' => 'Rue du Château 12, 1040 Echallens, Suisse',
                'lat' => 46.6413,
                'long' => 6.6348,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Musée du Vieux Montreux',
                'short_descr' => 'Musée historique.',
                'descr' => 'Le musée du Vieux Montreux conserve et présente l\'histoire locale de Montreux et de ses environs.',
                'adress_label' => 'Rue de la Gare 40, 1820 Montreux, Suisse',
                'lat' => 46.4337,
                'long' => 6.9105,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Musée Suisse du Jeu',
                'short_descr' => 'Musée des jeux.',
                'descr' => 'Situé dans le château de La Tour-de-Peilz, ce musée explore l\'histoire et la culture des jeux à travers le monde.',
                'adress_label' => 'Rue du Château 11, 1814 La Tour-de-Peilz, Suisse',
                'lat' => 46.4530,
                'long' => 6.8650,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Château de Morges',
                'short_descr' => 'Château et musée militaire.',
                'descr' => 'Le château de Morges abrite plusieurs musées, y compris le Musée militaire vaudois, présentant des expositions sur l\'histoire militaire.',
                'adress_label' => 'Rue du Château 1, 1110 Morges, Suisse',
                'lat' => 46.5104,
                'long' => 6.4980,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Le Jardin Botanique de Lausanne',
                'short_descr' => 'Jardin botanique.',
                'descr' => 'Ce jardin botanique à Lausanne offre une grande variété de plantes, des serres et des expositions sur la botanique.',
                'adress_label' => 'Avenue de Cour 14bis, 1007 Lausanne, Suisse',
                'lat' => 46.5155,
                'long' => 6.6265,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Musée Historique de Lausanne',
                'short_descr' => 'Musée historique.',
                'descr' => 'Ce musée, situé dans l\'ancien évêché, retrace l\'histoire de Lausanne depuis ses origines jusqu\'à nos jours.',
                'adress_label' => 'Place de la Cathédrale 4, 1005 Lausanne, Suisse',
                'lat' => 46.5222,
                'long' => 6.6369,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Parc de Mon Repos',
                'short_descr' => 'Parc public historique.',
                'descr' => 'Le parc de Mon Repos est un espace vert historique à Lausanne, idéal pour les promenades et les pique-niques, avec des jardins bien entretenus et des sculptures.',
                'adress_label' => 'Avenue Mon-Repos 14, 1005 Lausanne, Suisse',
                'lat' => 46.5191,
                'long' => 6.6386,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Église Saint-François',
                'short_descr' => 'Église historique.',
                'descr' => 'Cette église gothique située au centre de Lausanne est connue pour son architecture impressionnante et ses concerts d\'orgue.',
                'adress_label' => 'Place Saint-François, 1003 Lausanne, Suisse',
                'lat' => 46.5196,
                'long' => 6.6326,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Musée de la Main UNIL-CHUV',
                'short_descr' => 'Musée interactif sur la science et la santé.',
                'descr' => 'Ce musée propose des expositions interactives sur la santé, la médecine et les sciences humaines, avec des ateliers et des activités pour tous les âges.',
                'adress_label' => 'Route de la Corniche 10, 1010 Lausanne, Suisse',
                'lat' => 46.5262,
                'long' => 6.6513,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Place de la Palud',
                'short_descr' => 'Place publique historique.',
                'descr' => 'La Place de la Palud est une place animée de Lausanne, connue pour sa fontaine médiévale et son horloge animée qui raconte des histoires locales.',
                'adress_label' => 'Place de la Palud, 1003 Lausanne, Suisse',
                'lat' => 46.5230,
                'long' => 6.6336,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Musée Alexis Forel',
                'short_descr' => 'Musée d\'art et d\'histoire.',
                'descr' => 'Situé à Morges, ce musée présente des collections d\'art et des expositions temporaires dans un bâtiment historique.',
                'adress_label' => 'Grand-Rue 54, 1110 Morges, Suisse',
                'lat' => 46.5080,
                'long' => 6.4963,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'La Maison de la Rivière',
                'short_descr' => 'Centre nature et musée.',
                'descr' => 'Ce centre à Tolochenaz propose des expositions sur les écosystèmes fluviaux et des activités éducatives pour tous les âges.',
                'adress_label' => 'Chemin du Boiron 2, 1131 Tolochenaz, Suisse',
                'lat' => 46.5011,
                'long' => 6.4788,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Les Pléiades',
                'short_descr' => 'Site naturel et station de ski.',
                'descr' => 'Les Pléiades offrent des activités toute l\'année, y compris la randonnée, le ski et des vues panoramiques sur les Alpes et le lac Léman.',
                'adress_label' => 'Les Pléiades, 1807 Blonay, Suisse',
                'lat' => 46.4721,
                'long' => 6.9368,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Château de La Sarraz',
                'short_descr' => 'Château médiéval et musée.',
                'descr' => 'Ce château médiéval abrite un musée présentant l\'histoire de la région et des expositions d\'art.',
                'adress_label' => 'Rue du Château 1, 1315 La Sarraz, Suisse',
                'lat' => 46.6561,
                'long' => 6.5153,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Espace des Inventions',
                'short_descr' => 'Centre d\'exposition scientifique.',
                'descr' => 'Situé à Lausanne, l\'Espace des Inventions propose des expositions interactives sur divers thèmes scientifiques pour les jeunes et les familles.',
                'adress_label' => 'Vallée de la Jeunesse 1, 1007 Lausanne, Suisse',
                'lat' => 46.5193,
                'long' => 6.6116,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Château Saint-Maire',
                'short_descr' => 'Siège du gouvernement cantonal de Vaud.',
                'descr' => 'Le Château Saint-Maire est un château historique situé à Lausanne, qui abrite aujourd\'hui le gouvernement cantonal de Vaud.',
                'adress_label' => 'Place de la Cathédrale 4, 1005 Lausanne, Suisse',
                'lat' => 46.5223,
                'long' => 6.6361,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Domaine Croix Duplex',
                'short_descr' => 'Caveau de dégustation dans les vignobles de Lavaux.',
                'descr' => 'Le Domaine Croix Duplex est un vignoble situé dans la région de Lavaux, offrant un caveau de dégustation pour découvrir leurs vins.',
                'adress_label' => 'Route de la Corniche 5, 1091 Grandvaux, Suisse',
                'lat' => 46.4962,
                'long' => 6.7223,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Caveau de Dézaley',
                'short_descr' => 'Caveau de dégustation dans les vignobles de Lavaux.',
                'descr' => 'Le Caveau de Dézaley est un lieu de dégustation de vins situé dans la région de Lavaux, offrant une vue imprenable sur le lac Léman.',
                'adress_label' => 'Route de la Corniche 38, 1091 Puidoux, Suisse',
                'lat' => 46.4770,
                'long' => 6.7580,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Lakeside Promenade',
                'short_descr' => 'Belle promenade le long du lac Léman.',
                'descr' => 'La Lakeside Promenade est une belle promenade piétonne qui longe le lac Léman, offrant des vues magnifiques sur les montagnes et les eaux cristallines.',
                'adress_label' => 'Quai des Fleurs, 1820 Montreux, Suisse',
                'lat' => 46.4300,
                'long' => 6.9100,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Statue de Freddie Mercury',
                'short_descr' => 'Statue en hommage à Freddie Mercury.',
                'descr' => 'La statue de Freddie Mercury est un monument rendant hommage au chanteur légendaire de Queen, qui avait une résidence à Montreux et aimait profiter de la ville et de son lac.',
                'adress_label' => 'Quai du Marché, 1820 Montreux, Suisse',
                'lat' => 46.4330,
                'long' => 6.9130,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Casino de Montreux',
                'short_descr' => 'Lieu emblématique de Montreux, même si vous ne jouez pas.',
                'descr' => 'Le Casino de Montreux est un établissement de jeux et de divertissement situé sur les rives du lac Léman. Il propose des jeux de table, des machines à sous et accueille régulièrement des événements et des spectacles.',
                'adress_label' => 'Rue du Théâtre 9, 1820 Montreux, Suisse',
                'lat' => 46.4330,
                'long' => 6.9160,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Vignoble en terrasses (chemin de randonnée)',
                'short_descr' => 'Une magnifique randonnée à travers les vignobles en terrasses de Lavaux.',
                'descr' => 'Le chemin de randonnée des vignobles en terrasses de Lavaux offre des vues spectaculaires sur le lac Léman et les Alpes. Les vignobles, classés au patrimoine mondial de l\'UNESCO, sont un témoignage vivant de la tradition viticole de la région.',
                'adress_label' => 'Rte de la Corniche, 1091 Grandvaux, Suisse',
                'lat' => 46.4881,
                'long' => 6.7303,
                'accessibility' => false,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Läderach - Chocolatier Suisse',
                'short_descr' => 'Découvrez l\'art du chocolat suisse chez Läderach.',
                'descr' => 'Läderach est une chocolaterie suisse réputée pour ses chocolats de haute qualité et ses créations artisanales. Visitez leur boutique à Vevey pour déguster et acheter leurs délicieuses spécialités.',
                'adress_label' => 'Quai Perdonnet 25, 1800 Vevey, Suisse',
                'lat' => 46.4591,
                'long' => 6.8449,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
            [
                'title' => 'Palais de Rumine',
                'short_descr' => 'Un magnifique bâtiment abritant cinq musées et une bibliothèque.',
                'descr' => 'Le Palais de Rumine est un bâtiment emblématique de Lausanne, construit à la fin du 19ème siècle. Il abrite la Bibliothèque cantonale et universitaire, ainsi que cinq musées : archéologie et histoire, géologie, zoologie, monétaire et beaux-arts.',
                'adress_label' => 'Place de la Riponne 6, 1005 Lausanne, Suisse',
                'lat' => 46.5172,
                'long' => 6.6363,
                'accessibility' => true,
                'user_id' => DB::table('users')->where('pseudo', 'heig')->value('id'),
            ],
        ];

        foreach ($pois as $poi) {
            Poi::create($poi);
        }
    }
}
